### ISSUE TITLE
ffmpeg install via macports won't work

### ISSUE THREAD

**Issue by danrossi** [iliya-gr/mediasegmenter#1]
It's having a hard time building on mac with a macports installed ffmpeg. pkg-config doesn't pickup any of the libraries.

**Comment by sangwonl** [comment]
I would recommend following steps to install on your mac. I found it from https://github.com/3d0c/gmf

##### Build

build lastest version of ffmpeg, obtained from [https://github.com/FFmpeg/FFmpeg](https://github.com/FFmpeg/FFmpeg)  
There is one required option, which is disabled by default, you should turn on: `--enable-shared`  

E.g.:

``` sh
./configure --prefix=/usr/local/ffmpeg --enable-shared
make
make install
```

Add pkgconfig path:

``` sh
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/ffmpeg/lib/pkgconfig/
```

Ensure, that `PKG_CONFIG_PATH` contains path to ffmpeg's pkgconfig folder.

``` sh
# check it by running
pkg-config --libs libavformat
```

It should print valid path to the avformat library.

**Comment by danrossi** [comment]
closing this it's fine.
