### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Power2All** [iliya-gr/mediasegmenter#2]
Media Segmenter keeps using up more and more memory.
Eventually it's making the server swap when using the live option.

Any solution for this ?

**Comment by iliya-gr** [comment]
Hi Power2All, this project is not maintained since ffmpeg got better support for HLS (including live streaming). 
Please use ffmpeg instead.

**Comment by Power2All** [comment]
Hi,

Thanks, I noticed.
Already switched completely to FFMPEG now, all solved.
Thanks for reply.
